package com.gisroad.sign.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.gisroad.sign.bean.DepartBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEPART_BEAN".
*/
public class DepartBeanDao extends AbstractDao<DepartBean, Long> {

    public static final String TABLENAME = "DEPART_BEAN";

    /**
     * Properties of entity DepartBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property D_id = new Property(0, Long.class, "d_id", true, "_id");
        public final static Property D_name = new Property(1, String.class, "d_name", false, "D_NAME");
    }


    public DepartBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DepartBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEPART_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: d_id
                "\"D_NAME\" TEXT);"); // 1: d_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEPART_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DepartBean entity) {
        stmt.clearBindings();
 
        Long d_id = entity.getD_id();
        if (d_id != null) {
            stmt.bindLong(1, d_id);
        }
 
        String d_name = entity.getD_name();
        if (d_name != null) {
            stmt.bindString(2, d_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DepartBean entity) {
        stmt.clearBindings();
 
        Long d_id = entity.getD_id();
        if (d_id != null) {
            stmt.bindLong(1, d_id);
        }
 
        String d_name = entity.getD_name();
        if (d_name != null) {
            stmt.bindString(2, d_name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DepartBean readEntity(Cursor cursor, int offset) {
        DepartBean entity = new DepartBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // d_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // d_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DepartBean entity, int offset) {
        entity.setD_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setD_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DepartBean entity, long rowId) {
        entity.setD_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DepartBean entity) {
        if(entity != null) {
            return entity.getD_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DepartBean entity) {
        return entity.getD_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
